name: Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  dnsdist-e2e:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        dnsdist: [ "dnsdist-16", "dnsdist-17", "dnsdist-18", "dnsdist-19"   ]
        python: [ "3.8", "3.9", "3.10", "3.11", "3.12", "3.13" ]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python}}

    - name: Install Python requirements
      run: |
        python --version
        python -m pip install -r requirements.txt 
        python -m pip install --upgrade dnspython

    - name: Deploy dnsdist docker image
      run: |
        sudo docker run -d --network="host" --name=dnsdist --volume=$PWD/tests/dnsdist.conf:/etc/dnsdist/conf.d/dnsdist.conf:ro powerdns/${{ matrix.dnsdist}}
        sudo docker logs dnsdist
        until (dig -p 5553 www.github.com @127.0.0.1 | grep NOERROR); do sleep 5.0; done
        
    - name: Run Python tests
      run: |
        python -m unittest tests.test_console
        python -m unittest tests.test_key
        python -m unittest tests.test_statistics
        python -m unittest tests.test_hashpwd
